authors:
  timredz:
    name: Timur Redzhepov
    description: Algopack dev
    avatar: https://avatars.githubusercontent.com/u/50326291?v=4
    url: https://github.com/timredz
  squidfunk:
    name: Martin Donath
    description: Origin Creator
    avatar: https://avatars.githubusercontent.com/u/932156
    url: https://github.com/squidfunk
  alexvoss:
    name: Alex Voss
    description: Community support
    avatar: https://avatars.githubusercontent.com/u/4134224
    url: https://github.com/alexvoss
